# Generated by Django 5.1.2 on 2025-04-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0032_remove_file_ffprobe_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='codec',
            field=models.TextField(default='?'),
        ),
    ]
