# Generated by Django 5.1.2 on 2025-04-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0033_file_codec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='codec',
            field=models.TextField(),
        ),
    ]
