# Generated by Django 5.1.2 on 2024-10-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encodes', '0007_rename_encoder_profile_codec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodetask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Queued'), (2, 'Downloading'), (3, 'In Progress P1'), (4, 'In Progress'), (5, 'Uploading'), (6, 'Complete')], default=0),
        ),
    ]
