# Generated by Django 5.1.2 on 2025-04-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encodes', '0008_alter_encodetask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodetask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Queued'), (2, 'Downloading'), (3, 'In Progress (Pass 1)'), (4, 'In Progress'), (5, 'Uploading'), (6, 'Complete')], default=0),
        ),
    ]
