# Generated by Django 4.2.7 on 2024-08-01 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_alter_pooledmsssim_task_alter_pooledpsnr_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
